import fs from 'node:fs/promises';

const path='data/public-data.js';
let s=await fs.readFile(path,'utf8');
const marker='/* country-context-help-links-v1 */';
if(!s.includes(marker)){
  s += `\n${marker}\n(function(){\n  function applyHelp(){\n    document.querySelectorAll('.country-card .subgrid').forEach(grid=>{\n      const cols=[...grid.children];\n      if(cols.length<3)return;\n      for(const col of cols.slice(0,2)){\n        const rows=[...col.querySelectorAll('.small')];\n        let removed=0;\n        rows.forEach(row=>{\n          const t=row.textContent.trim();\n          if(/^[A-Z]{2}\\d+\\s*:/.test(t)){row.remove();removed++;}\n        });\n        if(removed && !col.querySelector('.small')){\n          const note=document.createElement('div');\n          note.className='small';\n          note.textContent='Regional names are not available in the source data, so code-only results are not shown.';\n          col.appendChild(note);\n        }\n      }\n      let d=grid.nextElementSibling;\n      if(!d || !d.classList.contains('context-help')){\n        d=document.createElement('details');\n        d.className='context-help';\n        grid.insertAdjacentElement('afterend',d);\n      }\n      d.innerHTML='<summary>What do these figures mean?</summary>' +\n        '<p><strong>Rainfall:</strong> percentages compare rainfall in the latest rolling one-month CHIRPS period with the long-term average. For example, <strong>+40%</strong> means about 40% more rainfall than average; <strong>-20%</strong> means about 20% less.</p>' +\n        '<p><strong>Regional rainfall:</strong> we only show subnational rainfall figures when the source provides a readable region/province name. Source codes such as ET02 or ZM108 are deliberately hidden because they are not meaningful to most users.</p>' +\n        '<p><strong>IPC Phase 3+:</strong> this is the estimated <em>number of people</em> in IPC Phase 3 (Crisis), Phase 4 (Emergency) or Phase 5 (Catastrophe/Famine), not a percentage.</p>' +\n        '<p><strong>Learn more:</strong> <a href="https://www.chc.ucsb.edu/data/chirps3" target="_blank" rel="noreferrer">About CHIRPS rainfall data ↗</a> · <a href="https://www.ipcinfo.org/ipcinfo-website/ipc-overview-and-classification-system/ipc-acute-food-insecurity/" target="_blank" rel="noreferrer">About the IPC food insecurity scale ↗</a> · <a href="https://www.ipcinfo.org/famine-facts/en/" target="_blank" rel="noreferrer">IPC Phase definitions ↗</a></p>';\n    });\n  }\n  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(applyHelp,0));else setTimeout(applyHelp,0);\n})();\n`;
  await fs.writeFile(path,s);
}
